### ISSUE TITLE
Failure to setup journald logging

### ISSUE THREAD

**Issue by eliliam** [TheShellLand/veilid-node-docker#2]
When running `bash run.sh` the container is created and started, but then immediately exits with the following error:
```
+ id
uid=105(veilid) gid=106(veilid) groups=106(veilid)
+ RUST_BACKTRACE=1
+ RUST_BACKTRACE=full
+ COLORBT_SHOW_HIDDEN=1
+ veilid-server
Error:
   0: failed to set up journald logging
   1: No such file or directory (os error 2)

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: color_eyre::config::EyreHook::into_eyre_hook::{{closure}}::h676a8536499f36e1
      at <unknown source file>:<unknown line>
   2: eyre::capture_handler::hf807a41f02dc72c6
      at <unknown source file>:<unknown line>
   3: eyre::error::<impl eyre::Report>::from_msg::hb349be9c60958ca6
      at <unknown source file>:<unknown line>
   4: veilid_server::veilid_logs::VeilidLogs::setup::h12d37774ac94d9cb
      at <unknown source file>:<unknown line>
   5: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h4c79bdda7d332c89
      at <unknown source file>:<unknown line>
   6: tokio::runtime::context::blocking::BlockingRegionGuard::block_on::ha91bd26e9471b705
      at <unknown source file>:<unknown line>
   7: veilid_server::tools::block_on::h84885fe4849c6722
      at <unknown source file>:<unknown line>
   8: veilid_server::main::{{closure}}::h33ba8f1bdece552b
      at <unknown source file>:<unknown line>
   9: veilid_server::main::hf85a4b235dc67802
      at <unknown source file>:<unknown line>
  10: std::sys_common::backtrace::__rust_begin_short_backtrace::h99ad9b59ed677e6b
      at <unknown source file>:<unknown line>
  11: main<unknown>
      at <unknown source file>:<unknown line>
  12: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  13: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

Did this work at one point in time or has it never worked?

**Comment by naisanzaa** [comment]
I raised an issue to their team

and this is what they said.

> There are a few conversations around this topic on Discord. Please search around and see where they are in their progress and join the discussion. We also already have an open issue similar to this one. 

Issue: https://gitlab.com/veilid/veilid/-/issues/314


And this was the related issue: 

https://gitlab.com/veilid/veilid/-/issues/251


## Linux system logging depends on journald

The only supported logging system on the Linux target seems to be journald which while common is not completely universal. It would be desirable for veilid to also support logging to syslog or straight to a file.

Current workaround to run veilid-server on Linux machines without systemd is to disable system logging completely.

'-s logging.system.enabled=false'

---

That was the next thing I was going to try

**Comment by naisanzaa** [comment]
merged.

**Comment by naisanzaa** [comment]
solved. built from source. veilid-server runs as expected now
